server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  #mybatis 配置文件所在路径
  type-aliases-package: com.xueliang.springcloud.entities  #所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml


spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver  #mysql驱动包
    url: jdbc:mysql://rm-2zehy4iye640j70e21o.mysql.rds.aliyuncs.com:3306/cloudDB01
    username: xueliangtest
    password: xueliangtest
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 300
